[project]
name = "ai-cif"
version = "0.1.0"
description = "AI for Pokémon Showdown"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anyio>=4.15.1",
    "dotenv>=0.9.9",
    "showdown-sdk",
    "tqdm>=4.70.1",
    "wandb>=0.30.0",
]


[dependency-groups]
dev = [
    "basedpyright>=1.40.1",
    "ruff>=0.16.7",
    "tqdm>=4.70.1",
]

[project.optional-dependencies]
cpu = [
    "torch",
    "torchvision",
]

rocm = [
    "torch",
    "torchvision",
    "pytorch-triton-rocm>=3.5.1",
    "triton-rocm>=3.6.0",
]

[tool.setuptools]
packages = ["ai_cif"]

[tool.setuptools.package-dir]
"" = "."

[tool.uv]
package = true

conflicts = [
    [
        { extra = "cpu" },
        { extra = "rocm" },
    ],
]

[tool.uv.sources]
showdown-sdk = { git = "https://forgejo.auragan.fr/AlexAuragan/Showdown-SDK.git" }
ai-cif = { workspace = true }

torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-rocm", extra = "rocm" },
]

torchvision = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-rocm", extra = "rocm" },
]

pytorch-triton-rocm = [
    { index = "pytorch-rocm", extra = "rocm" },
]

triton-rocm = [
    { index = "pytorch-rocm", extra = "rocm" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm7.2"
explicit = true


[tool.ruff]
line-length = 80

[tool.ruff.format]
skip-magic-trailing-comma = true


[tool.ruff.lint.isort]
split-on-trailing-comma = false
